# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ActiLink/ActiLink.sln
    - name: Build
      run: dotnet build ActiLink/ActiLink.sln --no-restore
    - name: Run Unit Tests
      run: dotnet test ActiLink/ActiLink.UnitTests/ActiLink.UnitTests.csproj --no-build --verbosity normal
    - name: Run Integration Tests
      run: dotnet test ActiLink/ActiLink.IntegrationTests/ActiLink.IntegrationTests.csproj --no-build --verbosity normal
